/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import t7p5e1.T7p5e1;

/**
 *
 * @author txaber
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaEntrada ve;
    private VentanaSalida vs;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    public VentanaPrincipal(String saludo) {
        initComponents();
        setLocationRelativeTo(null);
        lSaludo.setText("hola "+saludo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        bAlta = new javax.swing.JButton();
        bBaja = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bListaNE = new javax.swing.JButton();
        bListaD = new javax.swing.JButton();
        bListaC = new javax.swing.JButton();
        lSaludo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAlta = new javax.swing.JMenuItem();
        miModificar = new javax.swing.JMenuItem();
        miBaja = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miListaNE = new javax.swing.JMenuItem();
        miListaD = new javax.swing.JMenuItem();
        miListaC = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bAlta.setText("Alta");
        bAlta.setFocusable(false);
        bAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlta);

        bBaja.setText("Baja");
        bBaja.setFocusable(false);
        bBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBajaActionPerformed(evt);
            }
        });
        jToolBar1.add(bBaja);

        bModificar.setText("Modificar");
        bModificar.setFocusable(false);
        bModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bModificar);

        bListaNE.setText("listarPorNumeroEmpleado");
        bListaNE.setFocusable(false);
        bListaNE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListaNE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bListaNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaNEActionPerformed(evt);
            }
        });
        jToolBar1.add(bListaNE);

        bListaD.setText("listarPorDepartamento");
        bListaD.setFocusable(false);
        bListaD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListaD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bListaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaDActionPerformed(evt);
            }
        });
        jToolBar1.add(bListaD);

        bListaC.setText("listarPorContrato");
        bListaC.setFocusable(false);
        bListaC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListaC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bListaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaCActionPerformed(evt);
            }
        });
        jToolBar1.add(bListaC);

        lSaludo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lSaludo.setText("jLabel1");

        jLabel2.setText("indica operacion a realizar");

        jMenu1.setText("Personas");

        miAlta.setText("Alta");
        miAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaActionPerformed(evt);
            }
        });
        jMenu1.add(miAlta);

        miModificar.setText("Modificar");
        miModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarActionPerformed(evt);
            }
        });
        jMenu1.add(miModificar);

        miBaja.setText("Baja");
        miBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaActionPerformed(evt);
            }
        });
        jMenu1.add(miBaja);

        jMenu3.setText("Listar");

        miListaNE.setText("por numero de empleado");
        miListaNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaNEActionPerformed(evt);
            }
        });
        jMenu3.add(miListaNE);

        miListaD.setText("por departamento");
        miListaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaDActionPerformed(evt);
            }
        });
        jMenu3.add(miListaD);

        miListaC.setText("por contrato");
        miListaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaCActionPerformed(evt);
            }
        });
        jMenu3.add(miListaC);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(lSaludo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(lSaludo)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(0, 210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        T7p5e1.salir();
    }//GEN-LAST:event_mSalirActionPerformed

    private void miAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaActionPerformed
        ve = new VentanaEntrada(this,true,"alta");
        ve.setVisible(true);
    }//GEN-LAST:event_miAltaActionPerformed

    private void miModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarActionPerformed
        ve = new VentanaEntrada(this,true,"modificar");
        ve.setVisible(true);
    }//GEN-LAST:event_miModificarActionPerformed

    private void miBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaActionPerformed
        ve = new VentanaEntrada(this,true,"baja");
        ve.setVisible(true);
    }//GEN-LAST:event_miBajaActionPerformed

    private void miListaNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaNEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListaNEActionPerformed

    private void miListaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListaDActionPerformed

    private void miListaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListaCActionPerformed

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        miAlta.doClick();
    }//GEN-LAST:event_bAltaActionPerformed

    private void bBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBajaActionPerformed
        miBaja.doClick();
    }//GEN-LAST:event_bBajaActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        miModificar.doClick();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bListaNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaNEActionPerformed
        miListaNE.doClick();
    }//GEN-LAST:event_bListaNEActionPerformed

    private void bListaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaDActionPerformed
        miListaD.doClick();
    }//GEN-LAST:event_bListaDActionPerformed

    private void bListaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaCActionPerformed
        miListaC.doClick();
    }//GEN-LAST:event_bListaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bListaC;
    private javax.swing.JButton bListaD;
    private javax.swing.JButton bListaNE;
    private javax.swing.JButton bModificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lSaludo;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem miAlta;
    private javax.swing.JMenuItem miBaja;
    private javax.swing.JMenuItem miListaC;
    private javax.swing.JMenuItem miListaD;
    private javax.swing.JMenuItem miListaNE;
    private javax.swing.JMenuItem miModificar;
    // End of variables declaration//GEN-END:variables
}
